services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nexus_db
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/nexus_db?schema=public
      JWT_SECRET: supersecretkey
      PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
